### ISSUE TITLE
Maximum recursion depth exceeded for py>=3.9

### ISSUE THREAD

**Issue by marcodigennaro** [materialsproject/emmet#717]
``` pip install --upgrade emmet-core```
leads to the following error in python 3.9 or higher. 

```
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/marcodigennaro/miniconda3/envs/py3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/marcodigennaro/miniconda3/envs/py3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/Users/marcodigennaro/miniconda3/envs/py3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/Users/marcodigennaro/miniconda3/envs/py3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/Users/marcodigennaro/miniconda3/envs/py3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 547, in resolve
    return _build_result(state)
  File "/Users/marcodigennaro/miniconda3/envs/py3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 492, in _build_result
    if not _has_route_to_root(state.criteria, key, all_keys, connected):
  File "/Users/marcodigennaro/miniconda3/envs/py3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in _has_route_to_root
    if _has_route_to_root(criteria, pkey, all_keys, connected):
  File "/Users/marcodigennaro/miniconda3/envs/py3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in _has_route_to_root
    if _has_route_to_root(criteria, pkey, all_keys, connected):
  File "/Users/marcodigennaro/miniconda3/envs/py3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in _has_route_to_root
    if _has_route_to_root(criteria, pkey, all_keys, connected):
  [Previous line repeated 986 more times]
  File "/Users/marcodigennaro/miniconda3/envs/py3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 465, in _has_route_to_root
    for p in criteria[key].iter_parent():
RecursionError: maximum recursion depth exceeded
```

My system has recursion limit = 1000
```
import sys
print(sys.getrecursionlimit())
```

Beside, ```sys.setrecursionlimit(1500)``` (or higher),  
I think this could help:
https://stackoverflow.com/questions/5061582/setting-stacksize-in-a-python-script/16248113#16248113

**Comment by tsmathis** [comment]
Not sure what the issue was at the time, but I am not seeing any issues installing now, so marking this as closed.
